version: '3.1'

services:
  photolist:
    env_file: # NB env setter https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
      - ../configs/common.env
    build:
      context: ../.
      dockerfile: build/Dockerfile.Multistage
    image: photolist:latest
    links:
      - minio:minio
      - dbMysql:dbMysql
    volumes:
      - ../images:/app/images
      - ../configs/photolist.yaml:/etc/photolist.yaml
    depends_on:
      - "dbMysql"
      - "minio"
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photolist"]

  photoauth: # images auth app
    env_file:
      - ../configs/common.env
      - ../configs/photoauth.env
    image: photolist:latest
    links:
      - dbMysql:dbMysql
      - auth:auth
    volumes:
      - ../configs/photoauth.yaml:/etc/photoauth.yaml
    depends_on:
      - "dbMysql"
      - "photolist"
      - "auth"
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photoauth"]

  auth: # auth nano-service, session-manager for app
    env_file:
      - ../configs/common.env
      - ../configs/auth.env
    image: photolist:latest
    links:
      - dbMysql:dbMysql
    volumes:
      - ../configs/auth.yaml:/etc/auth.yaml
    depends_on:
      - "photolist"
      - "dbMysql"
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/auth"]


  dbMysql:
    image: mysql:8.0.17
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # paths relative to docker-compose files
      - ../dev:/docker-entrypoint-initdb.d
      - ../tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "love"
      MYSQL_DATABASE: photolist

  nginx:
    image: nginx:1.17
    links: # NB three services
      - minio:minio
      - photolist:photolist
      - photoauth:photoauth
    depends_on:
      - "photolist"
      - "photoauth"
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
    ports:
      - 8080:80

  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
    # что запускать и где данные храняться
    command: server /data
    volumes:
      - ../minio_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
