version: '3.1'

services:
  photolist:
    build:
      context: ../.
      dockerfile: build/Dockerfile.Multistage
    image: photolist:latest
    links:
      - minio:minio
      - dbMysql:dbMysql
    # only nginx port for app clients
    # ports:
      # - 8080:8080
    volumes:
      - ../images:/app/images
    depends_on:
      - "dbMysql"
      - "minio"
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photolist"]

  dbMysql:
    image: mysql:8.0.17
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # paths relative to docker-compose files
      - ../dev:/docker-entrypoint-initdb.d
      - ../tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "love"
      MYSQL_DATABASE: photolist

  nginx:
    image: nginx:1.17
    links:
      - minio:minio
      - photolist:photolist
    depends_on:
      - "photolist"
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
    ports:
      - 8080:80

  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
    # что запускать и где данные хранятся
    command: server /data
    volumes:
      - ../minio_data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
