version: '3.7'

services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
    # что запускать и где данные хранятся
    command: server /data
    volumes:
      - ./minio_data:/data

  nginx:
    image: nginx:1.17
    links:
      - minio:minio
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - 8081:80
