version: '3.7'

services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
      MINIO_ROOT_USER: access_123
      MINIO_ROOT_PASSWORD: secret_123
    volumes:
      - ./minio_data:/data
    command: server /data --console-address :9001

  nginx:
    image: nginx:1.17
    links:
      - minio:minio
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - 8081:80
