http:
  port: localhost:8082
db:
  host:     localhost:3306
  username: root
  password:
  database: photolist
s3: 
  host:   http://localhost:9000
  access: access_123
  secret: secret_123
  bucket: photolist
session: 
  type:   db
  secret: golangcourseSessionSecret
token: 
  type:   jwt
  secret: qsRY2e4hcM5T7X984E9WQ5uZ8Nty7fxB
example:
  yaml: "yaml config value"
