global:
  scrape_interval: 3s
scrape_configs:

 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090

 - job_name: coursera
   static_configs:
    - targets:
       - 127.0.0.1:8080
