version: '3.1'

services:

  dbMysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      # paths relative to docker-compose files
      - './_mysql/:/docker-entrypoint-initdb.d/'
      - /tmp/photolist/mysql:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: "love"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: photolist

  minio:
    image: minio/minio
    command: server /data --console-address :9001 # что запускать и где данные хранятся
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /tmp/photolist/minio_data:/data
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_ROOT_USER: access_123
      MINIO_SECRET_KEY: secret_123
      MINIO_ROOT_PASSWORD: secret_123

  nginx:
    image: nginx:1.17
    ports:
      - 8080:80
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
    links:
      - minio:minio
    # extra_hosts:
    #   - host.docker.internal:host-gateway
