// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Grpc5GatewayNothing grpc 5 gateway nothing
//
// swagger:model grpc_5_gatewayNothing
type Grpc5GatewayNothing struct {

	// dummy
	Dummy bool `json:"dummy,omitempty"`
}

// Validate validates this grpc 5 gateway nothing
func (m *Grpc5GatewayNothing) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this grpc 5 gateway nothing based on context it is used
func (m *Grpc5GatewayNothing) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Grpc5GatewayNothing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Grpc5GatewayNothing) UnmarshalBinary(b []byte) error {
	var res Grpc5GatewayNothing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
