// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Grpc5GatewaySessionID grpc 5 gateway session ID
//
// swagger:model grpc_5_gatewaySessionID
type Grpc5GatewaySessionID struct {

	// ID
	ID string `json:"ID,omitempty"`
}

// Validate validates this grpc 5 gateway session ID
func (m *Grpc5GatewaySessionID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this grpc 5 gateway session ID based on context it is used
func (m *Grpc5GatewaySessionID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Grpc5GatewaySessionID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Grpc5GatewaySessionID) UnmarshalBinary(b []byte) error {
	var res Grpc5GatewaySessionID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
