version: '3.1'

services:

  dbMysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - './_mysql/:/docker-entrypoint-initdb.d/'
      # - ../tmp/mysql:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: "love"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: photolist

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_SECRET_KEY: secret_123
      MINIO_ROOT_USER: access_123
      MINIO_ROOT_PASSWORD: secret_123
    command: server /data --console-address :9001
    volumes:
      - ../minio_data:/data

  nginx:
    image: nginx:1.17
    links:
      - minio:minio
      # - photolist:photolist
    # depends_on:
      # - "photolist"
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
    ports:
      - 8081:80

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8090:8080

  # photolist:
  #   build:
  #     context: ../.
  #     dockerfile: build/Dockerfile.Multistage
  #   image: photolist:latest
  #   links:
  #     - minio:minio
  #     - dbMysql:dbMysql
  #   # ports:
  #     # - 8080:8080
  #   volumes:
  #     - ../images:/app/images
  #   depends_on:
  #     - "dbMysql"
  #     - "minio"
  #   command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photolist"]
