// Code generated by go-swagger; DO NOT EDIT.

package auth_checker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new auth checker API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for auth checker API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	AuthCheckerCheck(params *AuthCheckerCheckParams, opts ...ClientOption) (*AuthCheckerCheckOK, error)

	AuthCheckerCreate(params *AuthCheckerCreateParams, opts ...ClientOption) (*AuthCheckerCreateOK, error)

	AuthCheckerDelete(params *AuthCheckerDeleteParams, opts ...ClientOption) (*AuthCheckerDeleteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
AuthCheckerCheck auth checker check API
*/
func (a *Client) AuthCheckerCheck(params *AuthCheckerCheckParams, opts ...ClientOption) (*AuthCheckerCheckOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAuthCheckerCheckParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AuthChecker_Check",
		Method:             "GET",
		PathPattern:        "/v1/session/check/{ID}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AuthCheckerCheckReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AuthCheckerCheckOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AuthCheckerCheckDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
AuthCheckerCreate auth checker create API
*/
func (a *Client) AuthCheckerCreate(params *AuthCheckerCreateParams, opts ...ClientOption) (*AuthCheckerCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAuthCheckerCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AuthChecker_Create",
		Method:             "POST",
		PathPattern:        "/v1/session/create",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AuthCheckerCreateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AuthCheckerCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AuthCheckerCreateDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
AuthCheckerDelete auth checker delete API
*/
func (a *Client) AuthCheckerDelete(params *AuthCheckerDeleteParams, opts ...ClientOption) (*AuthCheckerDeleteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAuthCheckerDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "AuthChecker_Delete",
		Method:             "POST",
		PathPattern:        "/v1/session/delete",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AuthCheckerDeleteReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AuthCheckerDeleteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*AuthCheckerDeleteDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
