// Code generated by go-swagger; DO NOT EDIT.

package auth_checker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"week07/grpc_5_gateway/swagger/sess-client/models"
)

// NewAuthCheckerDeleteParams creates a new AuthCheckerDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthCheckerDeleteParams() *AuthCheckerDeleteParams {
	return &AuthCheckerDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthCheckerDeleteParamsWithTimeout creates a new AuthCheckerDeleteParams object
// with the ability to set a timeout on a request.
func NewAuthCheckerDeleteParamsWithTimeout(timeout time.Duration) *AuthCheckerDeleteParams {
	return &AuthCheckerDeleteParams{
		timeout: timeout,
	}
}

// NewAuthCheckerDeleteParamsWithContext creates a new AuthCheckerDeleteParams object
// with the ability to set a context for a request.
func NewAuthCheckerDeleteParamsWithContext(ctx context.Context) *AuthCheckerDeleteParams {
	return &AuthCheckerDeleteParams{
		Context: ctx,
	}
}

// NewAuthCheckerDeleteParamsWithHTTPClient creates a new AuthCheckerDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthCheckerDeleteParamsWithHTTPClient(client *http.Client) *AuthCheckerDeleteParams {
	return &AuthCheckerDeleteParams{
		HTTPClient: client,
	}
}

/*
AuthCheckerDeleteParams contains all the parameters to send to the API endpoint

	for the auth checker delete operation.

	Typically these are written to a http.Request.
*/
type AuthCheckerDeleteParams struct {

	// Body.
	Body *models.Grpc5GatewaySessionID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth checker delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthCheckerDeleteParams) WithDefaults() *AuthCheckerDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth checker delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthCheckerDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth checker delete params
func (o *AuthCheckerDeleteParams) WithTimeout(timeout time.Duration) *AuthCheckerDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth checker delete params
func (o *AuthCheckerDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth checker delete params
func (o *AuthCheckerDeleteParams) WithContext(ctx context.Context) *AuthCheckerDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth checker delete params
func (o *AuthCheckerDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth checker delete params
func (o *AuthCheckerDeleteParams) WithHTTPClient(client *http.Client) *AuthCheckerDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth checker delete params
func (o *AuthCheckerDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the auth checker delete params
func (o *AuthCheckerDeleteParams) WithBody(body *models.Grpc5GatewaySessionID) *AuthCheckerDeleteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the auth checker delete params
func (o *AuthCheckerDeleteParams) SetBody(body *models.Grpc5GatewaySessionID) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AuthCheckerDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
