// Code generated by go-swagger; DO NOT EDIT.

package auth_checker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"week07/grpc_5_gateway/swagger/sess-client/models"
)

// AuthCheckerCreateReader is a Reader for the AuthCheckerCreate structure.
type AuthCheckerCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthCheckerCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthCheckerCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAuthCheckerCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAuthCheckerCreateOK creates a AuthCheckerCreateOK with default headers values
func NewAuthCheckerCreateOK() *AuthCheckerCreateOK {
	return &AuthCheckerCreateOK{}
}

/*
AuthCheckerCreateOK describes a response with status code 200, with default header values.

A successful response.
*/
type AuthCheckerCreateOK struct {
	Payload *models.Grpc5GatewaySessionID
}

// IsSuccess returns true when this auth checker create o k response has a 2xx status code
func (o *AuthCheckerCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this auth checker create o k response has a 3xx status code
func (o *AuthCheckerCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this auth checker create o k response has a 4xx status code
func (o *AuthCheckerCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this auth checker create o k response has a 5xx status code
func (o *AuthCheckerCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this auth checker create o k response a status code equal to that given
func (o *AuthCheckerCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the auth checker create o k response
func (o *AuthCheckerCreateOK) Code() int {
	return 200
}

func (o *AuthCheckerCreateOK) Error() string {
	return fmt.Sprintf("[POST /v1/session/create][%d] authCheckerCreateOK  %+v", 200, o.Payload)
}

func (o *AuthCheckerCreateOK) String() string {
	return fmt.Sprintf("[POST /v1/session/create][%d] authCheckerCreateOK  %+v", 200, o.Payload)
}

func (o *AuthCheckerCreateOK) GetPayload() *models.Grpc5GatewaySessionID {
	return o.Payload
}

func (o *AuthCheckerCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Grpc5GatewaySessionID)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthCheckerCreateDefault creates a AuthCheckerCreateDefault with default headers values
func NewAuthCheckerCreateDefault(code int) *AuthCheckerCreateDefault {
	return &AuthCheckerCreateDefault{
		_statusCode: code,
	}
}

/*
AuthCheckerCreateDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type AuthCheckerCreateDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this auth checker create default response has a 2xx status code
func (o *AuthCheckerCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this auth checker create default response has a 3xx status code
func (o *AuthCheckerCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this auth checker create default response has a 4xx status code
func (o *AuthCheckerCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this auth checker create default response has a 5xx status code
func (o *AuthCheckerCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this auth checker create default response a status code equal to that given
func (o *AuthCheckerCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the auth checker create default response
func (o *AuthCheckerCreateDefault) Code() int {
	return o._statusCode
}

func (o *AuthCheckerCreateDefault) Error() string {
	return fmt.Sprintf("[POST /v1/session/create][%d] AuthChecker_Create default  %+v", o._statusCode, o.Payload)
}

func (o *AuthCheckerCreateDefault) String() string {
	return fmt.Sprintf("[POST /v1/session/create][%d] AuthChecker_Create default  %+v", o._statusCode, o.Payload)
}

func (o *AuthCheckerCreateDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *AuthCheckerCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
