# https://github.com/cosmtrek/air/blob/master/air_example.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "/tmp"

[build]
  cmd = "go build --tags=dev -o /tmp/photolist_dev.bin ."
  bin = "photolist_dev.bin"
  full_bin = "bash -vxe ../../run.sh"
  log = "build-errors.log"
  include_dir = ["2_frontend"]
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css"]
  exclude_dir = ["images", "tmp", "vendor"]
  delay = 1500 # ms
  stop_on_error = true

  args_bin = []
  exclude_file = []
  exclude_regex = ["_foo_bar.go"]
  exclude_unchanged = false
  follow_symlink = false
    
  include_file = []
  kill_delay = "1s"
  
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true

[color]
  app = "white"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
