version: '3.1'
services:
  mysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE:=photolist
    volumes:
      # - './1_photolist_oauth/_mysql/:/docker-entrypoint-initdb.d/'
      - './2_frontend/_mysql/:/docker-entrypoint-initdb.d/'
