version: '3.1'

services:

  nginx:
    image: nginx:1.17
    ports:
      - 8080:80
    volumes:
      - ../configs/nginx:/etc/nginx/conf.d
    depends_on:
      - "photolist"
      - "photoauth"
      - "minio"
    links:
      - minio:minio
      - photolist:photolist
      - photoauth:photoauth
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  photolist:
    image: photolist:latest
    build:
      context: ../.
      dockerfile: build/Dockerfile.Multistage
    env_file:
      - ../configs/common.env
    environment:
      # docker compose -f ./deployments/docker-compose.yml --env-file ./secrets.env up
      - OAUTH_APP_ID=${OAUTH_APP_ID}
      - OAUTH_APP_SECRET=${OAUTH_APP_SECRET}
    volumes:
      - ../configs/photolist.yaml:/etc/photolist.yaml
      - /tmp/photolist/images:/app/images
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photolist", "-appid", "${OAUTH_APP_ID}", "-appsecret", "${OAUTH_APP_SECRET}"]
    depends_on:
      - "dbMysql"
      - "minio"
    links:
      - minio:minio
      - dbMysql:dbMysql
      - jaeger:jaeger

  photoauth:
    image: photolist:latest
    env_file:
      - ../configs/common.env
      - ../configs/photoauth.env
    volumes:
      - ../configs/photoauth.yaml:/etc/photoauth.yaml
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/photoauth"]
    depends_on:
      - "dbMysql"
      - "photolist"
      - "auth"
    links:
      - dbMysql:dbMysql
      - auth:auth
      - jaeger:jaeger

  auth:
    image: photolist:latest
    env_file:
      - ../configs/common.env
      - ../configs/auth.env
    volumes:
      - ../configs/auth.yaml:/etc/auth.yaml
    command: ["/app/wait-for-it.sh", "dbMysql:3306", "--", "/app/auth"]
    depends_on:
      - "photolist"
      - "dbMysql"
    links:
      - dbMysql:dbMysql
      - jaeger:jaeger

  dbMysql:
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      # paths relative to docker-compose files
      - './_mysql/:/docker-entrypoint-initdb.d/'
      - /tmp/photolist/mysql:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: "love"
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: photolist

  minio:
    image: minio/minio
    command: server /data --console-address :9001 # что запускать и где данные хранятся
    volumes:
      - /tmp/photolist/minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: access_123
      MINIO_ROOT_USER: access_123
      MINIO_SECRET_KEY: secret_123
      MINIO_ROOT_PASSWORD: secret_123

  # https://www.jaegertracing.io/docs/1.52/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - 16686:16686 #UI, 127.0.0.1:16686
      - 6831:6831
      - 9411:9411
      - 4317:4317
      - 4318:4318
    expose:
      - "6831"
      - "9411"
      - "4317"
      - "4318"
    environment:
      COLLECTOR_OTLP_ENABLED: true
