http: 
  port: localhost:8081
db:
  host:     localhost:3306
  username: root
  password:
  database: photolist
session: 
  type:   grpc
  grpc_addr: "localhost:10000"
example:
  yaml: "yaml config value"
