schema:
- api/schema.graphql
exec:
  filename: pkg/graphql/graphql_generated.go
model:
  filename: pkg/graphql/graphql_models_gen.go
resolver:
  filename: pkg/graphql/graphql_resolver.go
  type: Resolver

models:
  Photo:
    model: week11/photolist_pkglayout/pkg/photos.Photo
    fields:
      user:
        resolver: true
  User:
    model: week11/photolist_pkglayout/pkg/user.User
    fields:
      photos:
        resolver: true
      followed:
        resolver: true
      followedUsers:
        resolver: true
      recomendedUsers:
        resolver: true

autobind: []
